services:
    Vangrg\ProfanityBundle\Storage\ProfanitiesStorageDefault:
        arguments:
            - "%vangrg_profanity.source.file_name%"
            - "%vangrg_profanity.source.format%"
        public: true

    Vangrg\ProfanityBundle\Service\ProfanityChecker:
        arguments:
            - '@vangrg_profanity.storage'
            - '%vangrg_profanity.allow_bound_by_words%'
        public: true

    Vangrg\ProfanityBundle\Validator\Constraints\ProfanityCheckValidator:
        arguments:
            - '@vangrg_profanity.checker'
        tags:
            - { name: validator.constraint_validator }

    Vangrg\ProfanityBundle\Command\ProfanitiesPopulateCommand:
        arguments:
            $doctrine: '@doctrine'
            $profanityStorage: '@vangrg_profanity.storage.default'
        tags: ['console.command']
